version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:20.04
      
   steps:
      - run:
          no_output_timeout: 50m
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install nano bc bison ca-certificates curl flex gcc git libc6-dev libssl-dev openssl python ssh wget zip zstd sudo make clang gcc-arm-linux-gnueabi software-properties-common
           git config --global user.name "zebusen"
           git config --global user.email "zebusensei@gmail.com"
           git clone --depth=1 --quiet https://github.com/zebusen/myscript.git -b main
           script -c "bash -x myscript/compile.sh"
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
